-- PostgreSQL


-- Schema

DROP SCHEMA  IF EXISTS  assist_mater  CASCADE;
CREATE SCHEMA  assist_mater;

SET search_path TO assist_mater, public;


-- Tables

CREATE TABLE userr(
        id_user   INT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        lastname  VARCHAR (75) NOT NULL ,
        firstname VARCHAR (75) NOT NULL ,
        login     VARCHAR (50) NOT NULL ,
        password  VARCHAR (50) NOT NULL ,
        adress    VARCHAR (255) NOT NULL ,
        Phone     VARCHAR (25) NOT NULL,
	PRIMARY KEY (id_user)
);


CREATE TABLE contrat(
        id_contrat       INT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        lastname         VARCHAR (75) NOT NULL ,
        firstname        VARCHAR (75) NOT NULL ,
        date_naiss       DATE NOT NULL ,
        date_deb         DATE NOT NULL ,
        date_fin         DATE NOT NULL ,
        tarif_horaire    FLOAT NOT NULL ,
        indemn_entretien FLOAT NOT NULL ,
        indemn_repas     FLOAT NOT NULL ,
        id_user          INT NOT NULL,
	PRIMARY KEY (id_contrat),

	FOREIGN KEY (id_user) REFERENCES userr(id_user)
);


CREATE TABLE garde(
        id_garde   INT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        date_garde DATE NOT NULL ,
        heure_deb  TIME NOT NULL ,
        heure_fin  TIME NOT NULL,
        isRepasPris BOOLEAN NOT NULL,
        id_contrat  INT NOT NULL ,
	PRIMARY KEY (id_garde),
	
	FOREIGN KEY (id_contrat) REFERENCES contrat(id_contrat)
);


CREATE TABLE role(
        id_user       INT		 NOT NULL ,
        role          VARCHAR (20) NOT NULL ,
        CHECK( Role IN ('NOUNOU','PARENT') ),
	PRIMARY KEY (id_user,role),

	FOREIGN KEY (id_user) REFERENCES userr(id_user)
);


CREATE VIEW vue_userr_role AS
	SELECT u.login, r.role 
	FROM ( userr u
	INNER JOIN role r ON u.id_user = r.id_user );

	
-- Index userr

	
CREATE UNIQUE INDEX idx_userr_login ON userr (login ASC);
	
	
	
-- Compte utilisateur de la BD

DROP USER  IF EXISTS  assist_mater;
CREATE USER  assist_mater  WITH PASSWORD 'assist_mater';
GRANT ALL PRIVILEGES ON SCHEMA assist_mater TO assist_mater;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA assist_mater TO assist_mater;
	
	

